//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCFramework.SitioWeb.Usuario {
    
    
    public partial class vistaRendiciones {
        
        /// <summary>
        /// controlVistaRendiciones1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VCFramework.SitioWeb.controles.controlVistaRendiciones controlVistaRendiciones1;
    }
}
